### ISSUE TITLE
Failed install add-on v 0.9.0

### ISSUE THREAD

**Issue by suwatchai2** [PanJ/hassio-addons#5]
Failed to install add-on v 0.9.0
![2021-08-31_11-03-24](https://user-images.githubusercontent.com/70301928/131439923-a4334fa8-34d4-4bee-9c9a-1cd4eec22e40.jpg)

**Comment by PanJ** [comment]
Should be solved in `0.9.1` https://github.com/PanJ/hassio-addons/pull/7
